LANGUAGES = {}

LANGUAGES["en"] = {
	LangName = "English",
	AddOption = "Add option",
	Alive = "Alive",
	AllowFlashlight = "Can players use flashlight",
	AlreadyVoted = "You have already voted",
	AvoidPlayers = "Will push players from other players",
	Blue = "Blue",
	BlueSpawnPoints = "Spawn point for the blue team",
	BlueWon = "The winning team is blue",
	Bring = "Bring",
	CantDrop = "Weapons that players can't drop",
	ChatCommands = "Commands for vote for map change",
	ChatDead = "*DEAD*",
	ChatTeam = "(TEAM)",
	ChooseMap = "Choose the map",
	CopyName = "Copy name",
	CopySteamID = "Copy SteamID",
	Dead = "Dead",
	Deaths = "Deaths",
    Description = {
		"This gamemode cover a lot of different types of maps. There are 3 main types:\n1) Shooter. 2 teams are fighting with each other, the purpose of each of them - destroy the enemy team.\n2) Course. Can be 1 or 2 teams. Who first finished the map - won.\n3) Minigames. Includes previous 2 types. There are plenty of modes, one of which is selected automatically or by one of the players.\n\nGamemode creator - ",
		"СПУДИ МУН",
		".\n\nI express my thanks for the help 2 people:\n",
		"MrFisherMan",
		"\n",
		"Tommy",
		"\n\nTranslators: \n",
		"SERMAEX",
		" - spanish\n",
		"만렙 까마귀",
		" and ",
		"심심한 하루4",
		" - korean\n\nDownload the gamemode you can ",
		"here \n",
		"\n",
		"",
		"---\n",
		"\n",
		"Edited version by ",
		"Artūras \n",
		"2018/10/19 update."
	},
	DisableAutojump = "Disable autojump",
	DisableVoiceChat = "Disable voice chat",
	Done = "Done",
	Draw = "Draw",
	DrawPoints = "Points for a draw",
	DropAfterDeath = "Drop weapons after death",
	EditAllow = "Groups that have access to editor",
	EditNotification = "Enter \"%s\" in the chat to open the editor",
	Editor = "Editor",
	EditorCommand = "Commands to open the editor",
	EndTime = "Time after the end of the round",
	EnterMessage = "Enter message",
	EnterReason = "Enter reason",
	Exception = "Maps, which will not use in vote",
	FallDamage = "Will be counted damage by falling",
	FreezeTime = "Freezing time",
	Gag = "Gag",
	GamemodeCreator = "*GAMEMODE CREATOR*",
	GetPoints = "You get %i %s",
	God = "Immortality",
	Goto = "Goto",
	Gravity = "Gravity",
	Group = "Group",
	Groups = {
		"Groups description",
		"Group name",
		"Group priority",
		"Print name",
		"Color in RGB"
	},
	ID = "ID",
	InfiniteAmmo = "Infinite ammo",
	InvisibleOff = "Invisibility off",
	InvisibleOn = "Invisibility on",
	JumpPower = "Jump power",
	Kick = "Kick",
	LossPoints = "Points for a loss",
	MapWon = "%s won",
	MinVotes = "Minimal number of votes for the map change",
	Mute = "Mute",
	Name = "Name",
	NotEnough = "Not enough players",
	NumMaps = "The amount of maps added to the vote",
	NumRounds = "Number of rounds before change the map",
	OpenConfig = "Open the configuration",
	OpenSettings = "Open the map settings",
	Percent = "How many percent of players have to vote for changing map",
	Ping = "Ping",
	PlayerScale = "Multiplier of player size",
	PlayersDamage = "Players from different team able to attack each other",
	PlayersNoCollide = "Disable a collision of players",
	PlyInTeam = "How many players should be in red team, if team type = 4",
	PlyVoted = "%s voted for change the map (%i/%i)",
	Prefixes = "Prefixes, the text at the start of your map name",
	PreparationTime = "Preparation time",
	PreventMusic = "Disable music on the map",
	PrivateMessage = "Private message",
	RandomMessages = {
		string.format("Press %s to open menu", string.upper(input.LookupBinding("gm_showhelp") or "")),
		"You can download gamemode here\nhttp://steamcommunity.com/sharedfiles/filedetails/?id=1471687594",
		string.format("Press %s to equip a silencer", string.upper(input.LookupBinding("+attack2") or "")),
		"Enter \"!acts\" in the chat to open the acts list"
	},
	Red = "Red",
	RedSpawnPoints = "Spawn point for the red team",
	RedWon = "The winning team is red",
	RemoveOption = "Remove the option",
	Respawn = "Should players respawn",
	RestoreDefaults = "Restore the default",
	Restriction = "Only groups in the list can spectate (Command 'spectate')",
	RoundsLeft = "Rounds: %i",
	RoundStart = "The round has started",
	RunSpeed = "Run speed",
	Save = "Save",
	Score = "Score",
	SelectColor = "Select a color",
	SelectMap = "Select the map",
	Send = "Send",
	Slap = "Slap",
	Slay = "Slay",
	SortBy = "Sort by",
	SpectateGroups = "Groups which have access to spectate (Command 'spectate')",
	Spectators = "Spectators",
	Speed = "%.1f km/h",
	StartWeapon = "Start weapon",
	Survive = "You won and survived",
	TeamDamage = "Can teammates damage each others",
	TeamType = "1 - 1 team (all players need to die to end the round), 2 - 1 team (last player wins), 3 - 2 teams half-and-half, 4 - your own settings of 2 teams",
	Teleport = "Teleport",
	TempGod = "Time of immortality in the start of the round",
	Time = "Round time, counted in seconds",
	Ungag = "Ungag",
	Unmute = "Unmute",
	UsePrefixes = "Check map prefixes in the vote",
	ViewProfile = "View profile",
	VoteTime = "Time to vote",
	WalkSpeed = "Walk speed",
	Winner = "Winner: %s",
	WinPoints = "Points for the victory. If team type = 3, then all survived players will be given in 1.25 times more",
	Won = "You won",
	GetPointsName = function(points)
		if points == 1 then
			return "point"
		else
			return "points"
		end
	end
}

LANGUAGES["ru"] = {
	LangName = "Русский",
	AddOption = "Добавить опцию",
	Alive = "Жив",
	AllowFlashlight = "Могут ли игроки использовать фонарик",
	AlreadyVoted = "Вы уже проголосовали",
	AvoidPlayers = "Будет ли выталкивать игрока из других игроков",
	Blue = "Синие",
	BlueSpawnPoints = "Точка спавна для синей команды",
	BlueWon = "Победила команда синих",
	Bring = "К себе",
	CantDrop = "Оружие, которые игроки не могут выкинуть",
	ChatCommands = "Команды для голосования за смену карты",
	ChatDead = "*МЕРТВ*",
	ChatTeam = "(КОМАНДЕ)",
	ChooseMap = "Выберите карту",
	CopyName = "Скопировать имя",
	CopySteamID = "Скопировать SteamID",
	Dead = "Мертв",
	Deaths = "Смерти",
	Description = {
		"Этот режим поддерживает огромное количество карт. Можно выделить 3 основных типа:\n1) Стрелялка. 2 команды сражаются друг против друга, цель каждой из них - уничтожить вражескую команду.\n2) Прохождение. Может быть как 1, так и 2 команды. Кто первый прошел карту - победил.\n3) Миниигры. Включает предыдущие 2 типа. Есть большое количество режимов, один из которых выбирается автоматически или одним из игроков.\n\nСоздатель режима - ",
		"СПУДИ МУН",
		".\n\nВыражаю благодарности за помощь 2 людям:\n",
		"MrFisherMan",
		"\n",
		"Tommy",
		"\n\nПереводчики: \n",
		"SERMAEX",
		" - испанский\n",
		"만렙 까마귀",
		" и ",
		"심심한 하루4",
		" - корейский\n\nСкачать режим вы можете ",
		"здесь \n",
		"\n",
		"",
		"---\n",
		"\n",
		"Edited version by ",
		"Artūras \n",
		"2018/10/19 update."
	},
	DisableAutojump = "Отключить автораспрыжку",
	DisableVoiceChat = "Отключить голосовой чат",
	Done = "Готово",
	Draw = "Ничья",
	DrawPoints = "Поинты за ничью",
	DropAfterDeath = "Выкинуть оружие после смерти",
	EditAllow = "Группы, которые имеют права на редактор",
	EditNotification = "Напишите \"%s\" для открытия редактора",
	Editor = "Редактор",
	EditorCommand = "Команды для открытия редактора",
	EndTime = "Время после окончания раунда",
	EnterMessage = "Введите сообщение",
	EnterReason = "Введите причину",
	Exception = "Карты, которые не будут использованы при голосование",
	FallDamage = "Будет ли считаться урон от падений",
	FreezeTime = "Время заморозки",
	Gag = "Загагать",
	GamemodeCreator = "*СОЗДАТЕЛЬ РЕЖИМА*",
	GetPoints = "Вы получили %i %s",
	God = "Бессмертие",
	Goto = "К",
	Gravity = "Гравитация",
	Group = "Группа",
	Groups = {
		"Описание групп",
		"Имя группы",
		"Приоритет группы",
		"Имя для печати",
		"Цвет в RGB"
	},
	ID = "ID",
	InfiniteAmmo = "Бесконечные патроны",
	InvisibleOff = "Невидимость выключена",
	InvisibleOn = "Невидимость включена",
	JumpPower = "Сила прыжка",
	Kick = "Кикнуть",
	LossPoints = "Поинты за поражение",
	MapWon = "%s победила",
	MinVotes = "Минимальное количество голосов для смены карты",
	Mute = "Замутить",
	Name = "Имя",
	NotEnough = "Недостаточно игроков",
	NumMaps = "Количество карт, которые будут добавлены в голосование",
	NumRounds = "Число раундов перед сменой карты",
	OpenConfig = "Открыть конфигурацию",
	OpenSettings = "Открыть настройки карты",
	Percent = "Сколько игроков должно проголосовать за смену карты",
	Ping = "Пинг",
	PlayerScale = "Множитель размера игроков",
	PlayersDamage = "Могут ли игроки из разных команд атаковать друг друга",
	PlayersNoCollide = "Отключить столкновение игроков",
	PlyInTeam = "Количество людей в красной команде, если тип команд = 3",
	PlyVoted = "%s проголосовал за смену карты (%i/%i)",
	Prefixes = "Префиксы, текст в начале названия карты",
	PreparationTime = "Время подготовки",
	PreventMusic = "Отключить музыку на карте",
	PrivateMessage = "Личное сообщение",
	RandomMessages = {
		string.format("Нажмите %s для открытия меню", string.upper(input.LookupBinding("gm_showhelp") or "")),
		"Вы можете скачать режим здесь\nhttp://steamcommunity.com/sharedfiles/filedetails/?id=1471687594",
		string.format("Нажмите %s для того, чтобы установить глушитель", string.upper(input.LookupBinding("+attack2") or "")),
		"Введите \"!acts\" в чат чтобы открыть список актов"
	},
	Red = "Красные",
	RedSpawnPoints = "Точка спавна для красной команды",
	RedWon = "Победила команда красных",
	RemoveOption = "Удалить опцию",
	Respawn = "Должны ли люди возрождаться",
	RestoreDefaults = "Восстановить по умолчанию",
	Restriction = "Только группы, которые есть в списке, могут становиться наблюдателями (Команда 'spectate')",
	RoundsLeft = "Раундов: %i",
	RoundStart = "Раунд начался",
	RunSpeed = "Скорость бега",
	Save = "Сохранить",
	Score = "Очки",
	SelectColor = "Выберите цвет",
	SelectMap = "Выберите карту",
	Send = "Отправить",
	Slap = "Ударить",
	Slay = "Убить",
	SortBy = "Сортировать по",
	SpectateGroups = "Группы, которые могут становиться наблюдателями (Команда 'spectate')",
	Spectators = "Наблюдатели",
	Speed = "%.1f км/ч",
	StartWeapon = "Начальное оружие",
	Survive = "Вы победили и выжили",
	TeamDamage = "Могут ли товарищи по команде наносить урон друг другу",
	TeamType = "Тип разделение на команды. 1 - 1 команда, 2 - 2 команды пополам, 3 - ваши собственные настройки 2 карт",
	Teleport = "Телепорт",
	TempGod = "Время бессмертия в начале раунда",
	Time = "Время раунда, измеряется в секундах",
	Ungag = "Разгагать",
	Unmute = "Размутить",
	UsePrefixes = "Проверить префикс карт в голосование",
	ViewProfile = "Показать профиль",
	VoteTime = "Время на голосование",
	WalkSpeed = "Скорость ходьбы",
	Winner = "Победитель: %s",
	WinPoints = "Поинты за победу. Если тип команд = 2, то все выжившие игроки получат в 1.25 раз больше",
	Won = "Вы победили",
	GetPointsName = function(points)
		local hund = points % 100
		
		if hund >= 11 and hund <= 14 then
			return "поинтов"
		end
		
		local t = points % 10
		
		if t == 1 then
			return "поинт"
		end
		
		if t >= 2 and t <= 4 then
			return "поинта"
		end
		
		return "поинтов"
	end
}

LANGUAGES["esp"] = {
	LangName = "Espanol",
	AddOption = "Añadir opcion",
	Alive = "Vivo",
	AllowFlashlight = "Los jugadores pueden utilizar linterna",
	AlreadyVoted = "Ya has votado",
	AvoidPlayers = "Puedes empujar a otros jugadores",
	Blue = "Azul",
	BlueSpawnPoints = "Punto de spawn para el equipo rojo",
	BlueWon = "El ganador es el equipo azul",
	Bring = "Llevar",
	CantDrop = "Las armas no se pueden dropear",
	ChatCommands = "Comandos para votar cambio de mapa",
	ChatDead = "*MUERTO*",
	ChatTeam = "(EQUIPO)",
	ChooseMap = "Elegir mapa",
	CopyName = "Copiar nombre",
	CopySteamID = "Copiar SteamID",
	Dead = "Muerto",
	Deaths = "Muertes",
	Description = {
		"Este modo de juego tiene 3 modos principales:\n1) Disparos. 2 equipos luchan entre ellos.\n2) Circuito. Suelen ser 1 o 2 equipos. Quien termine el mapa primero - gana.\n3) Minijuegos. Incluidos los 2 anteriores. Este modo de juego es automatico del mapa, y cuando empiezas el primero que llegue a la meta gana.\n\nCreador del gamemode - ",
		"СПУДИ МУН",
		".\n\nCon la colaboracion de dos personas:\n",
		"MrFisherMan",
		"\n",
		"Tommy",
		"\n\nTraductores: \n",
		"SERMAEX",
		" - espanol\n",
		"만렙 까마귀",
		" y ",
		"심심한 하루4",
		" - coreano\n\nDescargate el gamemode ",
		"aqui \n",
		"\n",
		"",
		"---\n",
		"\n",
		"Edited version by ",
		"Artūras \n",
		"2018/10/19 update."
	},
	DisableAutojump = "Desactivar autosalto",
	DisableVoiceChat = "Desactivar chat de voz",
	Done = "Finalizado",
	Draw = "Empate",
	DrawPoints = "Puntos por empate",
	DropAfterDeath = "Caída de armas después de la muerte",
	EditAllow = "Grupos con acceso a editar",
	EditNotification = "Escribe \"%s\" en el chat para abrir el editor",
	Editor = "Editor",
	EditorCommand = "Comandos para abrir el editor",
	EndTime = "Tiempo después del final de la ronda",
	EnterMessage = "Poner mensaje",
	EnterReason = "Poner razon",
	Exception = "Mapas que no quieras que aparezcan",
	FallDamage = "Se cuenta el daño al caer",
	FreezeTime = "Tiempo muerto",
	Gag = "Gag",
	GamemodeCreator = "*CREADOR DEL GAMEMODE*",
	GetPoints = "Has conseguido %i %s",
	God = "Inmortalidad",
	Goto = "Ir a",
	Gravity = "Gravedad",
	Group = "Grupo",
	Groups = {
		"Descripcion de grupo",
		"Nombre de grupo",
		"Prioridad de grupo",
		"Nombre puesto",
		"Color en RGB"
	},
	ID = "ID",
	InfiniteAmmo = "Municion infinita",
	InvisibleOff = "Invisibilidad desactivada",
	InvisibleOn = "Invisibilidad activada",
	JumpPower = "Salto de poder",
	Kick = "Kick",
	LossPoints = "Puntos por perder",
	MapWon = "%s gano",
	MinVotes = "Minimos de votos para cambiar el mapa",
	Mute = "Mute",
	Name = "Nombre",
	NotEnough = "No hay suficientes jugadores",
	NumMaps = "Numero de mapas",
	NumRounds = "Numero de rondas para el cambio",
	OpenConfig = "Abrir configuracion",
	OpenSettings = "Abrir configuracion del mapa",
	Percent = "Cuanto porciento de personas para cambiar el mapa",
	Ping = "Ping",
	PlayerScale = "Multiplicar estatura de personaje",
	PlayersDamage = "Matanza entre equipos",
	PlayersNoCollide = "Desactivar colision de jugadores",
	PlyInTeam = "Cuantos jugadores tiene que haber en el equipo rojo? Por defecto = 3",
	PlyVoted = "%s ha votado por cambiar el mapa (%i/%i)",
	Prefixes = "Prefijos del mapa",
	PreparationTime = "Tiempo de preparacion",
	PreventMusic = "Desactivar musica en el mapa",
	PrivateMessage = "Mensaje privado",
	RandomMessages = {
		string.format("Apreta %s para abrir el menu", string.upper(input.LookupBinding("gm_showhelp") or "")),
		"Puedes descargar el gamemode de aqui\nhttp://steamcommunity.com/sharedfiles/filedetails/?id=1471687594",
		string.format("Apreta %s para silenciar el equipo", string.upper(input.LookupBinding("+attack2") or "")),
		"Escribe \"!acts\" en el chat para abrir el menu de acciones"
	},
	Red = "Rojo",
	RedSpawnPoints = "Punto de spawn para el equipo azul",
	RedWon = "El ganador es el equipo rojo",
	RemoveOption = "Eliminar opcion",
	Respawn = "Los jugadores van a respawnear",
	RestoreDefaults = "Devolver a la normalidad",
	Restriction = "Solo los grupos en el chat pueden espectar (Command 'spectate')",
	RoundsLeft = "Rondas: %i",
	RoundStart = "La ronda ha empezado",
	RunSpeed = "Velocidad de correr",
	Save = "Guardar",
	Score = "Puntos",
	SelectColor = "Seleccionar color",
	SelectMap = "Seleccionar mapa",
	Send = "Enviar",
	Slap = "Bofetada",
	Slay = "Matar",
	SortBy = "Ordenar por",
	SpectateGroups = "Grupos con acceso a espectado (Comando 'spectate')",
	Spectators = "Espectadores",
	Speed = "%.1f km/h",
	StartWeapon = "Empezar con arma",
	Survive = "Has ganado y sobrevivido",
	TeamDamage = "Fuego amigo",
	TeamType = "Tipo de distribucion de equipos. 1 - 1 equipo, 2 - 2 equipos de mitad y mitad, 3 - sus propios ajustes de 2 equipos",
	Teleport = "Teletransportar",
	TempGod = "Tiempo de inmortalidad cuando empiezas",
	Time = "Tiempo de ronda, en minutos",
	Ungag = "Ungag",
	Unmute = "Unmute",
	UsePrefixes = "Checkea los prefijos en el chat",
	ViewProfile = "Ver perfil",
	VoteTime = "Tiempo para votar",
	WalkSpeed = "Velocidad de correr",
	Winner = "Ganador: %s",
	WinPoints = "Puntos por la victoria. Si el tipo de equipo es = 2, entonces todo jugador superviviente se le dara una recompensa mayor por haber ganado",
	Won = "Has ganado",
	GetPointsName = function(points)
		if points == 1 then
			return "point"
		else
			return "points"
		end
	end
}

function GetText(key)
	if !LANGUAGES then return "" end
	
	if !CurLang then
		CurLang = "en"
	end
	
	if !LANGUAGES[CurLang] then
		local keys = table.GetKeys(LANGUAGES)
		
		if #keys == 0 then
			return ""
		end
		
		CurLang = table.Random(keys)
	end
	
	if LANGUAGES[CurLang] then
		if LANGUAGES[CurLang] and LANGUAGES[CurLang][key] then
			return LANGUAGES[CurLang][key]
		end
	end
	
	return ""
end

LANGUAGES["kr"] = {
	LangName = "한국어",
	AddOption = "옵션 추가",
	Alive = "생존",
	AllowFlashlight = "플레이어가 손전등을 사용할수 있게 합니다.",
	AlreadyVoted = "당신은 이미 투표했습니다.",
	AvoidPlayers = "플레이어가 대상을 밀수 있게 합니다.",
	Blue = "파랑",
	BlueSpawnPoints = "파랑 팀 스폰지점",
	BlueWon = "파랑 팀 승리!",
	Bring = "대상 부르기",
	CantDrop = "플레이어 무기드랍 방지 목록",
	ChatCommands = "맵 체인지 투표 명령어",
	ChatDead = "*사망*",
	ChatTeam = "(팀)",
	ChooseMap = "맵을 선택합니다.",
	CopyName = "닉네임 복사",
	CopySteamID = "스팀 고유번호 복사",
	Dead = "죽음",
	Deaths = "사망",
	Description = {
		"이 게임모드는 맵마다 유형이 달라 크게 4가지 나눕니다:\n1) 총격전 : 이 팀은 목적이 간단합니다. 상대 팀을 파괴시킵니다.\n2) 방 탈출 : 방 탈출은 함정을 피해 마지막까지 살아남거나 먼저 탈출한 사람이 이깁니다.\n3) 미니게임 : 미니게임은 한 맵에 여러가지 게임들을 통합 되어 있습니다.\n4) 데스런 : 데스런은 파랑팀이 탈출하는것이고 빨강팀은 파랑팀을 함정이나 도구 이용해서 죽입니다.\n\n게임모드 제작자 - ",
		"СПУДИ МУН",
		".\n\n모드 제작에 도와주신 고마운 분들\n",
		"MrFisherMan",
		"\n",
		"Tommy",
		"\n\n번역\n",
		"SERMAEX",
		" - 스페인\n",
		"만렙 까마귀",
		" 와 ",
		"심심한 하루4",
		" - 한국어\n\n게임모드를 다운받으려면 → ",
		"클릭 \n",
		"\n",
		"",
		"---\n",
		"\n",
		"Edited version by ",
		"Artūras \n",
		"2018/10/19 update."
	},
	DisableAutojump = "오토점프 사용안함",
	DisableVoiceChat = "보이스 사용안함",
	Done = "저장",
	Draw = "무승부!",
	DrawPoints = "무승부시 지급되는 포인트",
	DropAfterDeath = "죽은 후에 무기가 드랍되게 하는 옵션.",
	EditAllow = "에디터를 열 수 있는 그룹",
	EditNotification = "에디터를 열려면 \"%s\" 를 입력하세요",
	Editor = "에디터",
	EditorCommand = "에디터를 여는 명령어",
	EndTime = "라운드가 종료되고 나는 여유 시간",
	EnterMessage = "메세지를 입력하시오.",
	EnterReason = "이유를 입력하시오",
	Exception = "투표에 쓰이지 않을 맵 목록",
	FallDamage = "낙하에 의한 피해를 입는가에 대한 옵션.",
	FreezeTime = "게임 시작까지 대기 시간",
	Gag = "보이스 차단",
	GamemodeCreator = "*모드 개발자*",
	GetPoints = "당신은 %i %s 를 얻었다",
	God = "무적",
	Goto = "대상에게 이동",
	Gravity = "중력",
	Group = "그룹",
	Groups = {
		"그룹 설명",
		"그룹명",
		"그룹 우선순위",
		"새길 이름",
		"RGB 색상"
	},
	ID = "아이디",
	InfiniteAmmo = "무한 탄약",
	InvisibleOff = "투명 비활성화",
	InvisibleOn = "투명 활성화",
	JumpPower = "점프력",
	Kick = "킥",
	LossPoints = "패배시 지급되는 포인트",
	MapWon = "%s 맵 결정!",
	MinVotes = "맵 체인지를 위한 최소의 투표 수",
	Mute = "채팅 금지",
	Name = "닉네임",
	NotEnough = "플레이어가 충분하지 않습니다.",
	NumMaps = "투표할 맵 수",
	NumRounds = "맵 체인지까지 남은 라운드 설정",
	OpenConfig = "기본 설정",
	OpenSettings = "맵 설정",
	Percent = "맵을 변경하기 위해 투표를 해야 하는 플레이어의 비율",
	Ping = "지연 시간",
	PlayerScale = "플레이어 크기",
	PlayersDamage = "각 팀 플레이어를 서로 공격가능 하게 하게 합니다",
	PlayersNoCollide = "플레이어 간의 충돌을 끕니다.",
	PlyInTeam = "빨강팀 제한 인원수",
	PlyVoted = "%s 님이 맵 체인지를 위해 투표했습니다. (%i/%i)",
	Prefixes = "맵 체인지에 추가할 맵의 이름(예: mg_, surf)",
	PreparationTime = "준비 시간",
	PreventMusic = "맵 브금 사용안함",
	PrivateMessage = "개인 메세지",
	RandomMessages = {
		string.format("옵션 설정은 %s 키입니다", string.upper(input.LookupBinding("gm_showhelp") or "")),
		"게임모드는 여기서 다운로드 할 수 있습니다.\nhttp://steamcommunity.com/sharedfiles/filedetails/?id=1471687594",
		string.format("소음기는 %s 키로 착용합니다.", string.upper(input.LookupBinding("+attack2") or "")),
		"입력 \"!acts\" 동작 목록을 엽니다."
	},
	Red = "빨강",
	RedSpawnPoints = "빨강 팀 스폰지점",
	RedWon = "빨강 팀 승리!",
	RemoveOption = "옵션을 제거합니다",
	Respawn = "플레이어 부활",
	RestoreDefaults = "기본값 복원",
	Restriction = "관전자 (콘솔 명령어 'spectate') 를 할수 있게 합니다",
	RoundsLeft = "%i 라운드 남음",
	RoundStart = "라운드가 시작 되었습니다",
	RunSpeed = "달리는 속도",
	Save = "저장",
	Score = "점수",
	SelectColor = "색상을 선택합니다",
	SelectMap = "맵 투표목록",
	Send = "보내기",
	Slap = "튕기기",
	Slay = "죽이기",
	SortBy = "정렬",
	SpectateGroups = "관람을 할수 있는 권한이 있는 그룹 (콘솔 명령어 'spectate')",
	Spectators = "관전자",
	Speed = "%.1f km/h",
	StartWeapon = "시작 무기",
	Survive = "당신은 이기기 위해 살아남아야 합니다!",
	TeamDamage = "팀킬을 가능하게 합니다.",
	TeamType = "팀 분포 유형입니다. 1 - 1 팀, 2 - 2 팀, 3 - 2 팀 자신이 설정합니다.",
	Teleport = "텔레포트",
	TempGod = "라운드 시작시 무적 시간",
	Time = "라운드 시간",
	Ungag = "보이스 차단 풀기",
	Unmute = "채팅 금지 풀기",
	UsePrefixes = "투표할 맵 표시를 합니다.",
	ViewProfile = "프로필 보기",
	VoteTime = "투표 시간",
	WalkSpeed = "걷는 속도",
	Winner = "승리자: %s",
	WinPoints = "승리시 지급되는 포인트 (모두 살아 있을시 1.25 배 추가로 주어집니다.)",
	Won = "당신이 이겼습니다.",
	GetPointsName = function(points)
		if points == 1 then
			return "포인트"
		else
			return "포인트"
		end
	end
}